package collect

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"sync"

	"oem-ingest-new/internal/oem"
)

// ErrMetricGroupUnavailable marks a target/group pair that should not run as a
// collection job because OEM does not expose its metadata.
var ErrMetricGroupUnavailable = errors.New("grupo de metrica indisponivel")

// MetricGroupClient is the OEM client method required by MetadataCache.
type MetricGroupClient interface {
	MetricGroup(ctx context.Context, targetID, groupName string) (oem.MetricGroup, error)
}

// Logger is intentionally compatible with slog.Logger.
type Logger interface {
	WarnContext(context.Context, string, ...any)
}

// MetadataRequest identifies the target/group pair whose metadata is needed.
type MetadataRequest struct {
	TargetID        string
	TargetName      string
	MetricGroupName string
	Bodyless        bool
}

// GroupMetadata contains the key columns and metric definitions for one
// target/group pair. Keys can be empty for OEM groups without key columns and
// for custom/bodyless metrics generated by the collector.
type GroupMetadata struct {
	TargetID        string
	MetricGroupName string
	Keys            []string
	Metrics         []oem.MetricDefinition
	MetricByName    map[string]oem.MetricDefinition
	Bodyless        bool
}

// DataType returns the OEM data type for a metric column when metadata includes
// it. The bool is false when the metric is absent from the cached definition.
func (m GroupMetadata) DataType(metricName string) (string, bool) {
	def, ok := m.MetricByName[metricName]
	return def.DataType, ok
}

// MetadataUnavailableError describes a target/group pair disabled by metadata
// lookup. It matches ErrMetricGroupUnavailable with errors.Is.
type MetadataUnavailableError struct {
	TargetID        string
	TargetName      string
	MetricGroupName string
	StatusCode      int
	Err             error
}

func (e *MetadataUnavailableError) Error() string {
	target := e.TargetID
	if e.TargetName != "" {
		target = e.TargetName
	}
	if e.StatusCode > 0 {
		return fmt.Sprintf("grupo de metrica %q indisponivel para target %q: HTTP %d", e.MetricGroupName, target, e.StatusCode)
	}
	return fmt.Sprintf("grupo de metrica %q indisponivel para target %q", e.MetricGroupName, target)
}

func (e *MetadataUnavailableError) Unwrap() error {
	return e.Err
}

func (e *MetadataUnavailableError) Is(target error) bool {
	return target == ErrMetricGroupUnavailable
}

// MetadataCache keeps OEM metric group metadata in memory by target ID and
// metric group name.
type MetadataCache struct {
	client MetricGroupClient
	logger Logger

	mu       sync.RWMutex
	entries  map[metadataKey]metadataEntry
	inflight map[metadataKey]*metadataCall
}

// MetadataCacheOptions configures MetadataCache.
type MetadataCacheOptions struct {
	Logger Logger
}

type metadataKey struct {
	targetID string
	group    string
}

type metadataEntry struct {
	metadata GroupMetadata
	err      error
}

type metadataCall struct {
	done      chan struct{}
	entry     metadataEntry
	err       error
	cacheable bool
}

// NewMetadataCache creates an in-memory metadata cache. The client is required
// for regular OEM metric groups; bodyless requests can be resolved without it.
func NewMetadataCache(client MetricGroupClient, opts MetadataCacheOptions) *MetadataCache {
	return &MetadataCache{
		client:   client,
		logger:   opts.Logger,
		entries:  make(map[metadataKey]metadataEntry),
		inflight: make(map[metadataKey]*metadataCall),
	}
}

// Get returns cached metadata or fetches it from OEM before the first
// collection for the target/group pair.
func (c *MetadataCache) Get(ctx context.Context, req MetadataRequest) (GroupMetadata, error) {
	normalized, key, err := normalizeMetadataRequest(req)
	if err != nil {
		return GroupMetadata{}, err
	}

	// Bodyless/custom metadata can reuse a real OEM group name, such as
	// Response. Keep it out of the OEM metadata cache so empty custom keys do
	// not hide real group keys, and real group keys do not leak into bodyless
	// custom processing.
	if normalized.Bodyless {
		return bodylessMetadata(normalized), nil
	}

	if entry, ok := c.lookup(key); ok {
		return entry.result()
	}

	if call, ok := c.startOrJoin(key); ok {
		return c.waitForCall(ctx, call)
	}
	entry, cacheable, err := c.load(ctx, normalized)
	entry = c.finishCall(key, entry, cacheable, err)
	if !cacheable {
		return GroupMetadata{}, err
	}
	return entry.result()
}

func bodylessMetadata(req MetadataRequest) GroupMetadata {
	return GroupMetadata{
		TargetID:        req.TargetID,
		MetricGroupName: req.MetricGroupName,
		Bodyless:        true,
		MetricByName:    map[string]oem.MetricDefinition{},
	}
}

func (c *MetadataCache) load(ctx context.Context, req MetadataRequest) (metadataEntry, bool, error) {
	if c.client == nil {
		return metadataEntry{}, false, errors.New("collect: MetricGroupClient obrigatorio para metadata OEM")
	}
	group, err := c.client.MetricGroup(ctx, req.TargetID, req.MetricGroupName)
	if err != nil {
		if isHTTPStatus(err, http.StatusNotFound) {
			entry := metadataEntry{err: unavailableError(req, err)}
			c.warnUnavailable(ctx, req)
			return entry, true, nil
		}
		return metadataEntry{}, false, err
	}
	return metadataEntry{metadata: groupMetadata(req, group)}, true, nil
}

func (c *MetadataCache) lookup(key metadataKey) (metadataEntry, bool) {
	c.mu.RLock()
	defer c.mu.RUnlock()
	entry, ok := c.entries[key]
	return entry.clone(), ok
}

func (c *MetadataCache) startOrJoin(key metadataKey) (*metadataCall, bool) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.entries == nil {
		c.entries = make(map[metadataKey]metadataEntry)
	}
	if c.inflight == nil {
		c.inflight = make(map[metadataKey]*metadataCall)
	}
	if entry, ok := c.entries[key]; ok {
		call := &metadataCall{
			done:      make(chan struct{}),
			entry:     entry.clone(),
			cacheable: true,
		}
		close(call.done)
		return call, true
	}
	if call, ok := c.inflight[key]; ok {
		return call, true
	}
	call := &metadataCall{done: make(chan struct{})}
	c.inflight[key] = call
	return call, false
}

func (c *MetadataCache) waitForCall(ctx context.Context, call *metadataCall) (GroupMetadata, error) {
	select {
	case <-ctx.Done():
		return GroupMetadata{}, ctx.Err()
	case <-call.done:
		if !call.cacheable {
			return GroupMetadata{}, call.err
		}
		return call.entry.result()
	}
}

func (c *MetadataCache) finishCall(key metadataKey, entry metadataEntry, cacheable bool, err error) metadataEntry {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.entries == nil {
		c.entries = make(map[metadataKey]metadataEntry)
	}
	if cacheable {
		if existing, ok := c.entries[key]; ok {
			entry = existing.clone()
		} else {
			c.entries[key] = entry.clone()
		}
	}
	if call := c.inflight[key]; call != nil {
		call.entry = entry.clone()
		call.err = err
		call.cacheable = cacheable
		delete(c.inflight, key)
		close(call.done)
	}
	return entry.clone()
}

func (c *MetadataCache) warnUnavailable(ctx context.Context, req MetadataRequest) {
	if c.logger == nil {
		return
	}
	c.logger.WarnContext(ctx, "metadata de grupo de metrica indisponivel; job de coleta sera ignorado",
		"target_id", req.TargetID,
		"target_name", req.TargetName,
		"metric_group", req.MetricGroupName,
		"status_code", http.StatusNotFound,
	)
}

func (e metadataEntry) result() (GroupMetadata, error) {
	if e.err != nil {
		return GroupMetadata{}, e.err
	}
	return cloneMetadata(e.metadata), nil
}

func (e metadataEntry) clone() metadataEntry {
	return metadataEntry{
		metadata: cloneMetadata(e.metadata),
		err:      e.err,
	}
}

func normalizeMetadataRequest(req MetadataRequest) (MetadataRequest, metadataKey, error) {
	req.TargetID = strings.TrimSpace(req.TargetID)
	req.TargetName = strings.TrimSpace(req.TargetName)
	req.MetricGroupName = strings.TrimSpace(req.MetricGroupName)
	if req.TargetID == "" {
		return MetadataRequest{}, metadataKey{}, errors.New("metadata de grupo de metrica: target ID obrigatorio")
	}
	if req.MetricGroupName == "" {
		return MetadataRequest{}, metadataKey{}, errors.New("metadata de grupo de metrica: metric_group_name obrigatorio")
	}
	return req, metadataKey{targetID: req.TargetID, group: req.MetricGroupName}, nil
}

func groupMetadata(req MetadataRequest, group oem.MetricGroup) GroupMetadata {
	keys := make([]string, 0, len(group.Keys))
	for _, key := range group.Keys {
		name := strings.TrimSpace(key.Name)
		if name == "" {
			continue
		}
		keys = append(keys, name)
	}

	metrics := make([]oem.MetricDefinition, 0, len(group.Metrics))
	metricByName := make(map[string]oem.MetricDefinition, len(group.Metrics))
	for _, metric := range group.Metrics {
		name := strings.TrimSpace(metric.Name)
		if name == "" {
			continue
		}
		metric.Name = name
		metrics = append(metrics, metric)
		metricByName[name] = metric
	}

	return GroupMetadata{
		TargetID:        req.TargetID,
		MetricGroupName: req.MetricGroupName,
		Keys:            keys,
		Metrics:         metrics,
		MetricByName:    metricByName,
	}
}

func cloneMetadata(metadata GroupMetadata) GroupMetadata {
	out := metadata
	out.Keys = append([]string(nil), metadata.Keys...)
	out.Metrics = append([]oem.MetricDefinition(nil), metadata.Metrics...)
	out.MetricByName = make(map[string]oem.MetricDefinition, len(metadata.MetricByName))
	for name, def := range metadata.MetricByName {
		out.MetricByName[name] = def
	}
	return out
}

func unavailableError(req MetadataRequest, err error) error {
	var httpErr *oem.HTTPError
	statusCode := 0
	if errors.As(err, &httpErr) {
		statusCode = httpErr.StatusCode
	}
	return &MetadataUnavailableError{
		TargetID:        req.TargetID,
		TargetName:      req.TargetName,
		MetricGroupName: req.MetricGroupName,
		StatusCode:      statusCode,
		Err:             err,
	}
}

func isHTTPStatus(err error, statusCode int) bool {
	var httpErr *oem.HTTPError
	return errors.As(err, &httpErr) && httpErr.StatusCode == statusCode
}
