- name: oem-mock
  site: local
  endpoint: http://oem-mock:8008
  targets:
    - id: "240D79C7320E221DE06400144FFBE115"
      name: "occp40bc"
      typeName: "rac_database"
      tags:
        rac_database: "occp40bc"
        target_name: "occp40bc"
        target_type: "rac_database"
        ambiente: "local"
    - id: "3107639B0159F1634DCC581E477241AA"
      name: "occp40bc_occp40bc3"
      typeName: "oracle_database"
      tags:
        rac_database: "occp40bc"
        oracle_database: "occp40bc_occp40bc3"
        target_name: "occp40bc_occp40bc3"
        target_type: "oracle_database"
        ambiente: "local"
